# Generated by Django 3.1.7 on 2021-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyprediction',
            name='ground',
            field=models.CharField(choices=[('Chennai', 'Chennai'), ('Jaipur', 'Jaipur'), ('Nagpur', 'Nagpur'), ('Visakhapatnam', 'Visakhapatnam'), ('Raipur', 'Raipur'), ('Sharjah', 'Sharjah'), ('Hyderabad', 'Hyderabad'), ('Durban', 'Durban'), ('Kolkata', 'Kolkata'), ('Centurion', 'Centurion'), ('Ahmedabad', 'Ahmedabad'), ('Dharamsala', 'Dharamsala'), ('Port Elizabeth', 'Port Elizabeth'), ('Chandigarh', 'Chandigarh'), ('Ranchi', 'Ranchi'), ('OTHER', 'OTHER'), ('Bengaluru', 'Bengaluru'), ('Indore', 'Indore'), ('Rajkot', 'Rajkot'), ('Johannesburg', 'Johannesburg'), ('Pune', 'Pune'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('East London', 'East London'), ('Kimberley', 'Kimberley'), ('Abu Dhabi', 'Abu Dhabi'), ('Kanpur', 'Kanpur'), ('Delhi', 'Delhi'), ('Dubai', 'Dubai'), ('Cape Town', 'Cape Town'), ('Kochi', 'Kochi'), ('Cuttack', 'Cuttack'), ('Bloemfontein', 'Bloemfontein')], max_length=300),
        ),
    ]
