# Generated by Django 3.1.7 on 2021-09-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210924_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyprediction',
            name='ground',
            field=models.CharField(choices=[('Hyderabad', 'Hyderabad'), ('Sharjah', 'Sharjah'), ('Rajkot', 'Rajkot'), ('Centurion', 'Centurion'), ('East London', 'East London'), ('Indore', 'Indore'), ('Visakhapatnam', 'Visakhapatnam'), ('Kolkata', 'Kolkata'), ('Bangalore', 'Bangalore'), ('Port Elizabeth', 'Port Elizabeth'), ('Dubai', 'Dubai'), ('Jaipur', 'Jaipur'), ('Kimberley', 'Kimberley'), ('Kochi', 'Kochi'), ('OTHER', 'OTHER'), ('Cape Town', 'Cape Town'), ('Mumbai', 'Mumbai'), ('Chennai', 'Chennai'), ('Ranchi', 'Ranchi'), ('Ahmedabad', 'Ahmedabad'), ('Johannesburg', 'Johannesburg'), ('Bengaluru', 'Bengaluru'), ('Bloemfontein', 'Bloemfontein'), ('Nagpur', 'Nagpur'), ('Abu Dhabi', 'Abu Dhabi'), ('Delhi', 'Delhi'), ('Durban', 'Durban'), ('Kanpur', 'Kanpur'), ('Chandigarh', 'Chandigarh'), ('Pune', 'Pune'), ('Raipur', 'Raipur'), ('Cuttack', 'Cuttack'), ('Dharamsala', 'Dharamsala')], max_length=300),
        ),
    ]
