# Generated by Django 3.1.7 on 2021-09-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210924_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyprediction',
            name='ground',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Jaipur', 'Jaipur'), ('Chandigarh', 'Chandigarh'), ('Centurion', 'Centurion'), ('Ahmedabad', 'Ahmedabad'), ('Dharamsala', 'Dharamsala'), ('Visakhapatnam', 'Visakhapatnam'), ('Sharjah', 'Sharjah'), ('Chennai', 'Chennai'), ('Cape Town', 'Cape Town'), ('Cuttack', 'Cuttack'), ('Rajkot', 'Rajkot'), ('Ranchi', 'Ranchi'), ('East London', 'East London'), ('Johannesburg', 'Johannesburg'), ('Pune', 'Pune'), ('Abu Dhabi', 'Abu Dhabi'), ('Kanpur', 'Kanpur'), ('Nagpur', 'Nagpur'), ('Kolkata', 'Kolkata'), ('Bengaluru', 'Bengaluru'), ('Port Elizabeth', 'Port Elizabeth'), ('Kimberley', 'Kimberley'), ('Bangalore', 'Bangalore'), ('Mumbai', 'Mumbai'), ('Durban', 'Durban'), ('Indore', 'Indore'), ('Hyderabad', 'Hyderabad'), ('OTHER', 'OTHER'), ('Bloemfontein', 'Bloemfontein'), ('Raipur', 'Raipur'), ('Dubai', 'Dubai'), ('Kochi', 'Kochi')], max_length=300),
        ),
    ]
